language: ruby
cache: bundler

rvm: 2.5.1

os:
  - linux
  - osx

sudo: enabled

addons:
  apt:
    packages:
      - squashfs-tools
      - texinfo

before_install:
  - ./.travis/osx_deps.sh

before_script:
  - mksquashfs -version

script:
  - rake test
