language: ruby

rvm: 2.7.1

os: osx

osx_image: xcode7.3	

addons:
  apt:
    packages:
      - squashfs-tools

before_install:
  - brew update
  - brew install squashfs

before_script:
  - mksquashfs -version

script:
  - rake test
