language: ruby

sudo: enabled

rvm: 2.4.1

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq squashfs-tools

before_script:
  - mksquashfs -version
  - ruby --version

script:
  - ruby tests/ruby-compiler
