language: ruby

rvm: 2.4.0

os:
  - linux
  - osx

env:
  matrix:
    - RUBYC_TEST=ruby-compiler
    - RUBYC_TEST=homeland

addons:
  apt:
    packages:
      - cmake
      - squashfs-tools

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install squashfs; fi

script:
  - /bin/sh -x tests/$RUBYC_TEST
