language: ruby

rvm: 2.4.3

os:
  - linux
  - osx

sudo: enabled

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq squashfs-tools

before_script:
  - mksquashfs -version
  - ruby --version

script:
  - CPPFLAGS="-p" ruby tests/ruby-compiler
