language: ruby
cache: bundler

rvm: 2.4.3

os:
  - linux
  - osx

sudo: enabled

addons:
  apt:
    packages:
      - squashfs-tools
      - texinfo

before_install:
  - ./travis/osx_deps.sh

before_script:
  - mksquashfs -version
  - ruby --version

script:
  - rake test:unit
  - CPPFLAGS="-p" ruby tests/ruby-compiler
