name: macOS Catalina 10.15
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  make:
    runs-on: macos-10.15
    strategy:
      matrix:
        test_task: [ "check", "test-bundler-parallel", "test-bundled-gems", "leaked-globals" ]
        debug: ["", "--debug"]
      fail-fast: false
    env:
      GITPULLOPTIONS: --no-tags origin ${{github.ref}}
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Disable Firewall
        run: |
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate
      - name: git config
        run: |
          git config --global advice.detachedHead 0
      - uses: actions/checkout@v2
      - run: ./tool/actions-commit-info.sh
        id: commit_info
      - name: Install libraries
        run: |
          export WAITS='5 60'
          ruby/tool/travis_retry.sh brew upgrade
          ruby/tool/travis_retry.sh brew install gdbm gmp libffi openssl@1.1 zlib autoconf automake libtool readline
      - name: Set ENV
        run: |
          echo '::set-env name=JOBS::'-j$((1 + $(sysctl -n hw.activecpu)))
      - name: "[Enclose.io] Install libraries"
        run: |
          sw_vers
          export WAITS='5 60'
          ruby/tool/travis_retry.sh brew install squashfs
      - name: "[Enclose.io] Set ENV"
        run: |
          echo '::set-env name=ENCLOSE_IO_RUBYC_ADDTIONAL_ARGS::'${{ matrix.debug }}
          echo '::set-env name=ENCLOSE_IO_RUBYC_TEST_ENCLOSED_RUBY::'${{ matrix.test_task }}
      - name: "[Enclose.io] Set up Ruby"
        uses: ruby/setup-ruby@v1
      - name: "[Enclose.io] Install dependencies"
        run: bundle install
      - name: "[Enclose.io] Run rubocop"
        run: bundle exec rubocop
      - name: "[Enclose.io] Run tests"
        run: bundle exec rake
        env:
          RUBY_TESTOPTS: "-q --tty=no"
