name: macOS
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  make:
    strategy:
      matrix:
        os: [macos-10.15]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Disable Firewall
        run: |
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate
      - uses: actions/checkout@v2
      - name: Install libraries
        run: |
          export WAITS='5 60'
          ruby/tool/travis_retry.sh brew upgrade
          ruby/tool/travis_retry.sh brew install gdbm gmp libffi openssl@1.1 zlib autoconf automake libtool readline
      - name: "[rubyc] Install libraries"
        run: |
          sw_vers
          uname -a
          uname -p
          uname -m
          sysctl -n machdep.cpu.brand_string
          export WAITS='5 60'
          ruby/tool/travis_retry.sh brew install squashfs
          which mksquashfs
          mksquashfs -version
      - name: "[rubyc] Set up Ruby"
        uses: ruby/setup-ruby@v1
      - name: "[rubyc] Install dependencies"
        run: bundle install
      - name: "[rubyc] Run rubocop"
        run: bundle exec rubocop
      - name: "[rubyc] Run tests"
        run: bundle exec rake
      - name: "[rubyc] Create macOS Release"
        if: ${{ github.ref == 'refs/heads/master' &&	matrix.os == 'macos-10.15' && success() }}
        id: create_macos_release
        uses: pmq20/create-release@delete-old-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: darwin-x64
          release_name: Latest macOS Build
          draft: false
          prerelease: false
          replace_old_tag: true
      - name: "[rubyc] Upload macOS Release"
        if: ${{ github.ref == 'refs/heads/master' &&	matrix.os == 'macos-10.15' && success() }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_macos_release.outputs.upload_url }}
          asset_path: ./rubyc
          asset_name: rubyc
          asset_content_type: application/octet-stream
