name: Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  make:
    strategy:
      matrix:
        include:
          - os: windows-2019
            vs: 2019
          - os: windows-2016
            vs: 2017
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      GITPULLOPTIONS: --no-tags origin ${{github.ref}}
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
      - name: "[rubyc] Install libraries"
        run: |
          choco install --no-progress squashfs
      - name: "[rubyc] Set up Ruby"
        uses: ruby/setup-ruby@v1
      - name: "[rubyc] Install dependencies"
        run: bundle install
      - name: "[rubyc] Run rubocop"
        run: bundle exec rubocop
      - name: "[rubyc] Inspect Windows Environment"
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\${{ matrix.vs }}\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          set YACC=win_bison
          echo on
          wmic OS get OSArchitecture
          echo %PROCESSOR_ARCHITECTURE%
          set
          systeminfo
          where nmake
          where mksquashfs
          mksquashfs -version
          where ruby
          ruby -v
          where bundle
          bundle -v
        shell: cmd
      - name: "[rubyc] Run tests"
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\${{ matrix.vs }}\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          bundle exec rake
        shell: cmd
      - name: "[rubyc] Create Windows Release"
        if: ${{ github.ref == 'refs/heads/master' &&	matrix.os == 'windows-2016' && success() }}
        id: create_windows_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: windows
          release_name: Latest Windows Build
          draft: false
          prerelease: false
      - name: "[rubyc] Upload Windows Release"
        if: ${{ github.ref == 'refs/heads/master' &&	matrix.os == 'windows-2016' && success() }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_windows_release.outputs.upload_url }}
          asset_path: ./rubyc.exe
          asset_name: rubyc.exe
          asset_content_type: application/octet-stream
